### ISSUE TITLE
Status code 501

### ISSUE THREAD

**Issue by MariasStory** [Rishit-dagli/MIRNet-TFJS#12]
**Describe the bug**

**To Reproduce**
```
git clone git@github.com:Rishit-dagli/MIRNet-TFJS.git # or clone your own fork
cd MIRNet-TFJS
cd example # switch to the example folder
npm install
npm start
```

**Expected behavior**
```
Error: Failed to load SavedModel: Read less bytes than requested
         [[{{node RestoreV2}}]]
    at NodeJSKernelBackend.loadSavedModelMetaGraph (/home/myname/MIRNet-TFJS/example/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:401:29)
    at Object.<anonymous> (/home/myname/MIRNet-TFJS/example/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:446:45)
    at step (/home/myname/MIRNet-TFJS/example/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:48:23)
    at Object.next (/home/myname/MIRNet-TFJS/example/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:29:53)
    at fulfilled (/home/myname/MIRNet-TFJS/example/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:20:58)
undefined
Inside predict
TypeError: Cannot read property 'predict' of undefined
    at predict (/home/myname/MIRNet-TFJS/example/app.js:70:36)
    at async /home/myname/MIRNet-TFJS/example/app.js:125:22
POST /submit 501 9022.197 ms - 5
```
---------------------------------------------------------
node modeltest.js
===
```
Error: Failed to load SavedModel: Read less bytes than requested
         [[{{node RestoreV2}}]]
    at NodeJSKernelBackend.loadSavedModelMetaGraph (/home/myname/MIRNet-TFJS/example/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:401:29)
    at Object.<anonymous> (/home/myname/MIRNet-TFJS/example/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:446:45)
    at step (/home/myname/MIRNet-TFJS/example/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:48:23)
    at Object.next (/home/myname/MIRNet-TFJS/example/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:29:53)
    at fulfilled (/home/myname/MIRNet-TFJS/example/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:20:58)
Inside predict
TypeError: Cannot read property 'predict' of undefined
    at predict (/home/myname/MIRNet-TFJS/example/modeltest.js:43:46)
    at async /home/myname/MIRNet-TFJS/example/modeltest.js:74:5
DONE
```

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 87

**Comment by Rishit-dagli** [comment]
Hi @MariasStory ,
I would like to point out that [`variables.data-00000-of-00001`](https://github.com/Rishit-dagli/MIRNet-TFJS/blob/main/example/model/variables/variables.data-00000-of-00001) is a large file and is stored on LFS which might be the reason for this issue. In case you do not want to use LFS to download the original file you can download [the model](https://github.com/Rishit-dagli/MIRNet-TFJS/releases/download/v0.2.0/saved_model.tar.gz) and simply extract and save it under the [`model`](https://github.com/Rishit-dagli/MIRNet-TFJS/tree/main/example/model) directory.

**Comment by Rishit-dagli** [comment]
@MariasStory Please let me know if this issue is resolved?

**Comment by MariasStory** [comment]
Hi @Rishit-dagli,
Thank you for pointing the model location. I was able to run the web server by manually downloading the model.
I think that the instructions on your github page should be updated, to make sure that the results can be reporduced.
Also the demo on this page is not working: https://mirnet-tfjs.rishit.tech

I was hoping to enhance a darker photo from a webcam, but this solution is way to complex and the results from noisy samples were not satisfactorty.

**Comment by Rishit-dagli** [comment]
@MariasStory I was expecting folks to know and have installed Git LFS earlier which automatically fetches all the LFS objects while cloning, nevertheless I will update the instructions asking to install LFS first.

https://mirnet-tfjs.rishit.tech is no longer a valid URL, the GitHub repo and badge had already been updated with the new URL - https://mirnet-tfjs-demo.azurewebsites.net/

Could you share the image which you tried to enhance, so I could have a better look at it and investigate accordingly? Also what aspect of this seemed complex, this would help me better enhance the instructions?
